services:
  scraper:
    build:
      context: .
      dockerfile: ./compose/mixer/Dockerfile.local
      args:
      - UID=1000
      - GID=1000
    volumes:
    - ./:/app
    container_name: mixer_local
    environment:
    - PYDEVD_WARN_SLOW_RESOLVE_TIMEOUT=2
    - PYDEVD_DISABLE_FILE_VALIDATION=1
    - PYTHONDONTWRITEBYTECODE=1
    command: sleep infinity
    ports:
    - 5679:5679

